---
- name: Setting Up Server 2
  hosts: server2
  strategy: free
  ignore_errors: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    hostname: name=server2.rhcsa8lab.example.com
  - name: Configuring Network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.77.3/24 ipv4.gateway 192.168.77.1 ipv4.dns 8.8.8.8 ipv4.dns-search rhcsa8lab.example.com ipv4.method manual
  - name: Reloading Network
    service:
      name: NetworkManager
      state: restarted
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "172.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1      localhost localhost.localdomain localhost6 localhost6.localdomain6\n192.168.77.2 server1.rhcsa8lab.example.com server1\n192.168.77.3 server2.rhcsa8lab.example.com server2"
  - name: Enabling IPV6
    sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
    with_items:
      - net.ipv6.conf.lo.disable_ipv6
      - net.ipv6.conf.all.disable_ipv6
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message Then Rebooting
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
        #!/bin/bash
        #
        echo -e '
        #        _,--*dSS|""I$$$SS%cccc,_
        #      <$$$b |$$$l  j$$$$$$$$$$$$$Sbp
        #       ?$$$b|$$$$  d$$$$$$$$$$$$$$P
        #        ?$$$$$$$$; $$$$$$$$$$$$$$P
        #         ?$$$$$$$| $$$$$$$$$$$$$P
        #          )$$$$$$$_$SSSSS$$$$$$(
        #          Y"'               """P
        #          (                    )   
        #  _.,cccccd%S$$$$$$$$$$$$$$$SS%dcccc,._
        # ($$$$$$$$$$SSSSSSSSSSSSSSS$$$$$$$$$$$$$$$)
        #  `"""""Y"'                  `"$$$$$$$P"'
        #
        '"#
        # You are logged into \"`hostname`\" as the \"`whoami`\" account.
        # This system is running `cat /etc/redhat-release`
        #
        # For root - use \`sudo\` or \`sudo su -\`
        #
        "
  - name: Adjusting Services and Rebooting
    selinux:
      state: permissive
      policy: targeted

  become: true
  